name: coolweather
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: '>=0.11.3+12'
  quiver: '>=2.0.0 <3.0.0'
  json_annotation: ^2.0.0
  shared_preferences: ^0.5.3+4
  amap_location:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/green.jpg
    - images/sunny.jpg
    - images/ic_home.png
    - images/cw_cloud.png
    - images/cw_sunny.png
    - images/cw_wind.png
    - images/cw_local.png
    - images/cw_snow.png
    - images/cl_light_rain.png
    - images/cl_nosun.png
    - images/cl_rain.png
    - images/location_ic.png
    - images/cw_haze.png
    - images/main_bg_1.jpg
    - images/main_bg_2.png
    - images/building_ic.png
    - images/weather/cloud_ic.png
    - images/weather/haze_ic.png
    - images/weather/nosun_ic.png
    - images/weather/rain_ic.png
    - images/weather/snow_ic.png
    - images/weather/sunny_ic.png
    - images/weather/wind_ic.png


  fonts:
    - family: Oxygen-Regular
      fonts:
        - asset: assets/fonts/Oxygen-Regular.ttf
    - family: Oxygen-Light
      fonts:
        - asset: assets/fonts/Oxygen-Light.ttf